In [1]:
#1. Convert List to 1D Array
import numpy as np
a = [1, 2, 3, 4, 5]
a = np.array(a)
print(a)

[1 2 3 4 5]


In [2]:
#2 Create 3x3 Matrix (2?10)
import numpy as np
a = np.arange(2, 11).reshape(3, 3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
#3. Null Vector (10) & Update Sixth Value
a = np.zeros(10)
a[5] = 11
print(a)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [4]:
#4. Array from 12 to 38
array = np.arange(12, 39)
print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [6]:
#5 Conver array to float type
a = np.array([1, 2, 3, 4])
a = a.astype(float)
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [7]:
#6 . Celsius to Fahrenheit Conversion
c = np.array([0, 12, 45.21, 34, 99.91])
f = (c * 9/5) + 32
print(f)

[ 32.     53.6   113.378  93.2   211.838]


In [8]:
#7. Append values to array
a = np.array([1, 2, 3])
a = np.append(a, [4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [10]:
#8. Array statistics functions
a = np.random.rand(10)
mean = np.mean(a)
median = np.median(a)
std = np.std(a)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)



Mean: 0.45622542169843594
Median: 0.3951627984848749
Standard Deviation: 0.31761536837948706


In [11]:
#9. find min and max values
a = np.random.rand(10)
min_value = np.min(a)
max_value = np.max(a)
print("Min:", min_value)
print("Max:", max_value)

Min: 0.20617749565349874
Max: 0.9863909258376883


In [12]:
#10 Create a 3x3x3 array with random values.
a = np.random.rand(3, 3, 3)
print(a)
print(a.shape)

[[[0.84399629 0.16544272 0.42015268]
  [0.12921031 0.95900983 0.96653247]
  [0.43184387 0.23303094 0.62873356]]

 [[0.49502094 0.10537801 0.39803955]
  [0.54296526 0.585772   0.00986847]
  [0.43056523 0.27505376 0.32355254]]

 [[0.73122421 0.26350441 0.4198862 ]
  [0.39678592 0.79275844 0.73853565]
  [0.83173246 0.06723759 0.27031392]]]
(3, 3, 3)
